modules:
  - type: dnf
    install:
      packages:
        - alacritty
        - fish
        - just
        - Thunar
        - thunar-volman
        - thunar-archive-plugin
        - thunar-media-tags-plugin
        - xarchiver
        - tumbler
        - ffmpegthumbnailer
        - gnome-disk-utility
        - udiskie
        - unzip
        - unrar
        - p7zip
        - p7zip-plugins
        - zip
        - bzip2
        - mpv         # Video player
        - qimgv       # Image viewer
        - okular      # PDF viewer
        - featherpad  # Text editor
        - inkscape
        - gimp
        - rawtherapee
        - "@libreoffice"
        - firefox
        - chromium