# Cerulean Just Commands
# Run with: cjust <command>

# Default recipe to display help
default:
    @just --list --unsorted

# Import module files
import? "just/10-update.just"
import? "just/20-thinkpad.just"
